# Generated by Django 3.1.1 on 2020-10-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200918_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='distance',
            field=models.CharField(choices=[('M', 'mi'), ('K', 'km')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.CharField(choices=[('P', 'lbs'), ('K', 'kg')], default='P', max_length=1),
        ),
    ]
