# Generated by Django 3.1.1 on 2020-10-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201002_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='distance',
            new_name='distance_units',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='weight',
            new_name='weight_units',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_weight',
            field=models.FloatField(default=0),
        ),
    ]
