# Generated by Django 3.1.1 on 2020-10-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201002_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_weight',
            new_name='weight',
        ),
    ]
