# Generated by Django 3.1.1 on 2020-10-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_goal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_resistance',
            field=models.BooleanField(default=False),
        ),
    ]
