# Generated by Django 3.1.1 on 2020-12-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201219_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hide_resistance',
        ),
    ]
