# Generated by Django 3.1.1 on 2020-10-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
