# Generated by Django 3.1.1 on 2020-10-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20200928_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Workout', max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.session')),
            ],
        ),
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('workout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.workout')),
            ],
            bases=('log.workout',),
        ),
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('workout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.workout')),
            ],
            bases=('log.workout',),
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('workout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.workout')),
            ],
            bases=('log.workout',),
        ),
    ]
