# Generated by Django 3.1.1 on 2020-12-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20201005_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rworkout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wlworkout',
            name='user',
        ),
        migrations.DeleteModel(
            name='CWorkout',
        ),
        migrations.DeleteModel(
            name='RWorkout',
        ),
        migrations.DeleteModel(
            name='WLWorkout',
        ),
    ]
