# Generated by Django 3.1.1 on 2020-10-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_cardio_resistance_weight_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
